### ISSUE TITLE
[general] create modal with beta notice for initial startup

### ISSUE THREAD

**Issue by ItsANameToo** [ArkEcosystem/payvo-wallet#1088]
### Describe the refactor you'd like to request

More details will follow, but it will contain a modal that will be shown on first visit indicating that it's a beta product.

**Note that this modal will replace the current ToS en privacy policy line that is available on creation of a profile, so that has to be removed during beta testing**

**Comment by boldninja** [comment]
This modal is going to be only visible while we perform Beta testing and will be disabled and replaced by Privacy Policy & Terms of Use in the profile creation step.

When the user visits Payvo Wallet for the first time we show this modal:
![payvobeta](https://user-images.githubusercontent.com/25795454/156793150-7dff746c-6e1c-4cf7-a8b6-4613929f7b10.png)

By default, we don't tick the checkbox as the user needs to consent with outlined terms. The 'Continue' button is grayed out:
![payvob](https://user-images.githubusercontent.com/25795454/156793372-39c83073-5e76-437e-9752-468c2f241075.png)

If they don't consent they don't have to do anything but close the tab of the wallet. If they want to use the wallet they have to tick the checkbox 'I agree, don’t show this again.', which also turns the 'Continue' button into an actionable event:
![betap](https://user-images.githubusercontent.com/25795454/156794549-78e1ee32-413f-4283-a2e4-7f839656f7d9.png)

 By pressing Continue we show the default Payvo Wallet screen so they can create a Profile and start using it.

![payvow](https://user-images.githubusercontent.com/25795454/156794703-d58ea117-04a7-4f3c-a820-ce5361f9489f.png)

**_Figma design:_**  https://www.figma.com/file/o6b1tEMOdUtHv7ijVs6pMX/Payvo-DW?node-id=6799%3A152927

Consent is saved as a localstorage/cookie so that modal doesn't get shown until someone clears the cache for the site.

**Comment by alfonsobries** [comment]
PR https://github.com/ArkEcosystem/payvo-wallet/pull/1205
